apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
  labels:
    app: worker
    tier: worker
    pdb-test: no-pdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        tier: worker
        pdb-test: no-pdb
        version: v1.5
    spec:
      containers:
      - name: worker-process
        image: busybox:1.35
        command: ['sh', '-c', 'while true; do echo "$(date): Processing job batch..."; sleep 60; done']
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 1Gi
        env:
        - name: SERVICE_NAME
          value: "worker"
        - name: ENVIRONMENT
          value: "test"
        - name: BATCH_SIZE
          value: "50"
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: metrics-collector
        image: busybox:1.35
        command: ['sh', '-c', 'while true; do echo "$(date): Collecting metrics for worker"; sleep 45; done']
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
